language: go

go:
  - 1.10.x

before_install:
  # We need golang/dep installed to resolve our dependencies
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure

script: make build test
